version: "3"

services:
  postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ${VOLUME_PATH}
    restart: always
    networks:
      - postgres-compose-network
networks:
  postgres-compose-network:
    driver: bridge
